#!/usr/bin/env python3
import senseglove_finger_distance.finger_distance_node
import sys

if __name__ == '__main__':
    senseglove_finger_distance.finger_distance_node.main(sys.argv[1], sys.argv[2])
