FROM nvidia_ros_melodic:latest
 
# Change the default shell to Bash
SHELL [ "/bin/bash" , "-c" ]
 
# Install Git & ros_control
RUN apt-get update && apt-get install -y git \
 && apt-get install -y ros-melodic-ros-control ros-melodic-ros-controllers \
 && apt-get install -y python-catkin-tools \
 && apt-get install -y build-essential
 
# Create a Catkin workspace and clone TurtleBot3 repos
RUN source /opt/ros/melodic/setup.bash \
 && git clone https://github.com/Adjuvo/senseglove_ros_ws
 
# Build the Catkin workspace and ensure it's sourced
RUN source /opt/ros/melodic/setup.bash \
 && cd senseglove_ros_ws/ \
 && catkin_make
RUN echo "source /senseglove_ros_ws/devel/setup.bash" >> ~/.bashrc
 
# Set the working folder at startup
WORKDIR /senseglove_ros_ws
