controller:
  joint_state:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  hand_state:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  trajectory:
    type: position_controllers/JointTrajectoryController # Position interface because we are directly passing on commands
    allow_partial_joints_goal: true
    publish_rate: 100
    joints:
      - r_thumb_brake # FFB
      - r_index_brake # FFB
      - r_middle_brake # FFB
      - r_ring_brake # FFB
      - r_pinky_brake # FFB
      - r_thumb_cmc # Buzzer
      - r_index_mcp # Buzzer
      - r_middle_mcp # Buzzer
      - r_ring_mcp # Buzzer
      - r_pinky_mcp # Buzzer
