# MIT License
# Copyright (c) 2023 TommyChangUMD

# ---------------------------------------------------------------------
# This Dockerfile is derived from:
#   https://github.com/TommyChangUMD/ros-jazzy-ros1-bridge-builder
# Original author: TommyChangUMD (2023)
# License: MIT (see LICENSE-upstream.txt)
#
# Modifications by: Akshay Radhamohan Menon (akshay@senseglove.com)
#   • Replaced original tarball commands with ENTRYPOINT lines at the end
#   • Renamed file to Dockerfile.ros2_bridge
# ---------------------------------------------------------------------

FROM ros:jazzy-ros-base-noble

# Make sure bash catches errors (no need to chain commands with &&, use ; instead)
SHELL ["/bin/bash", "-o", "pipefail", "-o", "errexit", "-c"]

ARG DEBIAN_FRONTEND=noninteractive

###########################
# 1.) Bring system up to the latest ROS desktop configuration
###########################
RUN apt update && \
    apt install -y --no-install-recommends \
        ros-jazzy-desktop \
        ros-jazzy-ros2-control \
        ros-jazzy-ros2-controllers && \
    rm -rf /var/lib/apt/lists/*

###########################
# 2.) Temporarily remove ROS2 apt repository
###########################
RUN mv /etc/apt/sources.list.d/ros2.sources /root/
RUN apt-get update

###########################
# 3.) comment out the catkin conflict
###########################
RUN sed  -i -e 's|^Conflicts: catkin|#Conflicts: catkin|' /var/lib/dpkg/status
RUN apt-get install -f

###########################
# 4.) force install these packages (after restoring ros2.sources)
###########################
# Temporarily bring back ROS 2 sources to access python3-rosdistro
RUN cp /root/ros2.sources /etc/apt/sources.list.d/ros2.sources && \
    apt-get update && \
    apt-get download python3-catkin-pkg && \
    apt-get download python3-rospkg && \
    apt-get download python3-rosdistro && \
    mv /etc/apt/sources.list.d/ros2.sources /root/

# Install with force-overwrite
RUN dpkg --force-overwrite -i python3-catkin-pkg*.deb
RUN dpkg --force-overwrite -i python3-rospkg*.deb
RUN dpkg --force-overwrite -i python3-rosdistro*.deb
RUN apt-get install -f

###########################
# 6.) Restore the ROS2 apt repos and update again
###########################
RUN mv /root/ros2.sources /etc/apt/sources.list.d/
RUN apt-get -y update

###########################
# 5.) Install ROS1 Noetic desktop
# (Currently, ppa contains AMD64 builds only)
###########################
RUN apt update; \
    apt -y install software-properties-common; \
    rm -rf /var/lib/apt/lists/*
RUN add-apt-repository ppa:ros-for-jammy/noble
RUN apt update; \
    apt -y install ros-noetic-desktop; \
    rm -rf /var/lib/apt/lists/*

# fix ARM64 pkgconfig path issue -- Fix provided by ambrosekwok 
RUN if [[ $(uname -m) = "arm64" || $(uname -m) = "aarch64" ]]; then                     \
      cp /usr/lib/x86_64-linux-gnu/pkgconfig/* /usr/lib/aarch64-linux-gnu/pkgconfig/;   \
    fi

COPY ./shared/senseglove_shared_resources_msgs.tar.xz .
RUN tar -xJf senseglove_shared_resources_msgs.tar.xz && \
    rm senseglove_shared_resources_msgs.tar.xz

# Compile for ROS1:
RUN cd senseglove_shared_resources_msgs/ros1 && \
    unset ROS_DISTRO && source /opt/ros/noetic/setup.bash && \ 
    time colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
                 
# Compile for ROS2:
RUN cd senseglove_shared_resources_msgs/ros2 && \                                           
    source /opt/ros/jazzy/setup.bash && \                                                   
    time colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release     

RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
RUN echo "source /opt/ros/jazzy/setup.bash"  >> ~/.bashrc
RUN echo "source /senseglove_shared_resources_msgs/ros1/install/setup.bash" >> ~/.bashrc
RUN echo "source /senseglove_shared_resources_msgs/ros2/install/setup.bash" >> ~/.bashrc

###########################
# 7.) Compile ros1_bridge
###########################

# g++-11 and needed
RUN apt update; \
    apt -y install g++-11 gcc-11; \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 11; \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 11; \
    rm -rf /var/lib/apt/lists/*

RUN                                                                                     \
     #-------------------------------------                                             \
     # Get the Bridge code                                                              \
     #-------------------------------------                                             \
     mkdir -p /ros-jazzy-ros1-bridge/src;                                               \
     cd /ros-jazzy-ros1-bridge/src;                                                     \
     git clone -b action_bridge_humble https://github.com/smith-doug/ros1_bridge.git;   \
     cd ros1_bridge/;                                                                   \
                                                                                        \
     #-------------------------------------                                             \
     # Apply the ROS1 and ROS2 underlays                                                \
     #-------------------------------------                                             \
     source /opt/ros/noetic/setup.bash;                                                 \
     source /opt/ros/jazzy/setup.bash;                                                  \
     source /senseglove_shared_resources_msgs/ros1/install/setup.bash;                  \
     source /senseglove_shared_resources_msgs/ros2/install/setup.bash;                  \
                                                                                        \
     #-------------------------------------                                             \
     # Finally, build the Bridge                                                        \
     #-------------------------------------                                             \
     MEMG=$(printf "%.0f" $(free -g | awk '/^Mem:/{print $2}'));                        \
     NPROC=$(nproc);  MIN=$((MEMG<NPROC ? MEMG : NPROC));                               \
     cd /ros-jazzy-ros1-bridge/;                                                        \
     echo "Please wait...  running $MIN concurrent jobs to build ros1_bridge";          \
     time ROS_DISTRO=humble MAKEFLAGS="-j $MIN" colcon build                            \
       --event-handlers console_direct+                                                 \
       --cmake-args -DCMAKE_BUILD_TYPE=Release

###########################
# 9.) Pack all ROS1 dependent libraries
###########################
# fix ARM64 pkgconfig path issue -- Fix provided by ambrosekwok 
RUN if [[ $(uname -m) = "arm64" || $(uname -m) = "aarch64" ]]; then                    \
      cp /usr/lib/x86_64-linux-gnu/pkgconfig/* /usr/lib/aarch64-linux-gnu/pkgconfig/;  \
    fi

RUN ROS1_LIBS="libactionlib.so";                                                \
    ROS1_LIBS="$ROS1_LIBS libroscpp.so";                                        \
    ROS1_LIBS="$ROS1_LIBS librosconsole.so";                                    \
    ROS1_LIBS="$ROS1_LIBS libroscpp_serialization.so";                          \
    ROS1_LIBS="$ROS1_LIBS librostime.so";                                       \
    ROS1_LIBS="$ROS1_LIBS libxmlrpcpp.so";                                      \
    ROS1_LIBS="$ROS1_LIBS libcpp_common.so";                                    \
    ROS1_LIBS="$ROS1_LIBS librosconsole_log4cxx.so";                            \
    ROS1_LIBS="$ROS1_LIBS librosconsole_backend_interface.so";                  \
    ROS1_LIBS="$ROS1_LIBS liblog4cxx.so.15";                                    \
    ROS1_LIBS="$ROS1_LIBS libaprutil-1.so.0";                                   \
    ROS1_LIBS="$ROS1_LIBS libapr-1.so.0";                                       \
    cd /ros-jazzy-ros1-bridge/install/ros1_bridge/lib;                          \
    source /opt/ros/noetic/setup.bash;                                          \
    for soFile in $ROS1_LIBS; do                                                \
      soFilePath=$(ldd libros1_bridge.so | grep $soFile | awk '{print $3;}');   \
      cp -L $soFilePath ./;                                                     \
    done

# ###########################
# # 10.) Spit out ros1_bridge tarball by default when no command is given
# ###########################
RUN tar czf /ros-jazzy-ros1-bridge.tgz \
     --exclude '*/build/*' --exclude '*/src/*' /ros-jazzy-ros1-bridge 

###########################
# 6) Copy entrypoint and default to launching dynamic_bridge
###########################
COPY ./entrypoints/rosbridge_1to2_entrypoint.sh /rosbridge_1to2_entrypoint.sh
RUN chmod +x /rosbridge_1to2_entrypoint.sh

ENTRYPOINT ["/rosbridge_1to2_entrypoint.sh"]
CMD ["ros2", "run", "ros1_bridge", "dynamic_bridge", "--bridge-all-topics"]
