FROM osrf/ros:noetic-desktop-full

ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_WORKSPACE=/root/ros1_ws

# ROS1-GPG Key Fix
RUN rm /etc/apt/sources.list.d/ros1-latest.list && \
    apt-key del "C1CF 6E31 E6BA DE88 68B1  72B4 F42E D6FB AB17 C654"

RUN apt-get update && apt-get install -y curl && \
    sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list' && \
    curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -

RUN apt-get update && apt-get install -y software-properties-common build-essential lsb-release gnupg wget \
    python3-pip python-is-python3 python3-catkin-tools python3-pyqt5 \
    ros-noetic-ros-control ros-noetic-joint-trajectory-controller ros-noetic-joint-state-publisher \
    ros-noetic-rviz ros-noetic-tf2-ros \
    udev bluez ros-noetic-rosserial-python ros-noetic-rospy-tutorials \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y software-properties-common wget lsb-release gnupg

RUN mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://apt.kitware.com/keys/kitware-archive-latest.asc \
    | gpg --dearmor -o /etc/apt/keyrings/kitware.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/kitware.gpg] \
    https://apt.kitware.com/ubuntu/ focal main" \
    > /etc/apt/sources.list.d/kitware.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends cmake && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p ${ROS_WORKSPACE}/src
WORKDIR ${ROS_WORKSPACE}

RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc && \
    echo "source ${ROS_WORKSPACE}/devel/setup.bash" >> ~/.bashrc

COPY ./entrypoints/ros1_entrypoint.sh /ros1_entrypoint.sh
RUN chmod +x /ros1_entrypoint.sh
ENTRYPOINT ["/ros1_entrypoint.sh"]
CMD ["bash"]