FROM osrf/ros:noetic-desktop-full

ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_WORKSPACE=/root/ros1_ws

RUN apt-get update && apt-get install -y software-properties-common build-essential lsb-release gnupg wget \
    python3-pip python-is-python3 python3-catkin-tools python3-pyqt5 \
    ros-noetic-ros-control ros-noetic-joint-trajectory-controller ros-noetic-joint-state-publisher \
    ros-noetic-rviz ros-noetic-tf2-ros \
    udev bluez ros-noetic-rosserial-python ros-noetic-rospy-tutorials \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y software-properties-common wget lsb-release gnupg

RUN mkdir -p ${ROS_WORKSPACE}/src
WORKDIR ${ROS_WORKSPACE}

RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc && \
    echo "source ${ROS_WORKSPACE}/devel/setup.bash" >> ~/.bashrc

COPY ./entrypoints/ros1_entrypoint.sh /ros1_entrypoint.sh
RUN chmod +x /ros1_entrypoint.sh
ENTRYPOINT ["/ros1_entrypoint.sh"]
CMD ["bash"]