/**/controller_manager:
  ros__parameters:
    update_rate: 60    

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

/**/haptics_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - r_thumb_brake   # FFB
      - r_index_brake   # FFB
      - r_middle_brake  # FFB
      - r_ring_brake    # FFB
      - r_pinky_brake   # FFB
      - r_thumb_dip     # Buzzer
      - r_index_dip     # Buzzer
      - r_middle_dip    # Buzzer
      - r_ring_dip      # Buzzer
      - r_pinky_dip     # Buzzer
    interface_name: effort