services:
  senseglove_ros:
    build:
      context: .
      dockerfile: Dockerfile.ros2
      args:
        ROS_DISTRO: jazzy 
    privileged: true
    network_mode: host
    volumes:
      - ../:/root/workspace/src/senseglove_ros:rw
      - ./entrypoint.sh:/entrypoint.sh:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - /var/run/dbus:/var/run/dbus:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DISTRO=jazzy
      - ROS_DOMAIN_ID=0
      - XDG_RUNTIME_DIR=/tmp/runtime-root
    group_add:
      - dialout
      - bluetooth 
    tty: true
    stdin_open: true