services:
  senseglove_ros:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ros1
    privileged: true
    network_mode: host
    devices:
      - /dev:/dev
    volumes:
      - ../:/root/ros1_ws/src/senseglove_ros:rw
      - ./entrypoints/ros1_entrypoint.sh:/root/ros1_entrypoint.sh:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - CMAKE_POLICY_VERSION_MINIMUM=3.5
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=localhost
    tty: true
    stdin_open: true
  rosbridge_1to2:
    profiles: ["rosbridge_1to2"]
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.rosbridge_1to2
    image: rosbridge_1to2
    network_mode: host
    environment:
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=localhost
    tty: true
    stdin_open: true
    depends_on:
      - senseglove_ros

  # ros1_bridge binary
  host_rosbridge_tgz:
    profiles: ["host_rosbridge_tgz"]
    image: rosbridge_1to2
    entrypoint: []
    command: cat /ros-jazzy-ros1-bridge.tgz