ARG ROS_DISTRO=jazzy
FROM osrf/ros:${ROS_DISTRO}-desktop-full

ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_WORKSPACE=/root/workspace

RUN apt-get update && apt-get install -y \
        build-essential git ninja-build software-properties-common lsb-release wget curl gnupg \
        python3-pip python-is-python3 \
        python3-colcon-common-extensions python3-rosdep python3-pyqt5 \
        ros-${ROS_DISTRO}-ros2-control ros-${ROS_DISTRO}-ros2-controllers \
        ros-${ROS_DISTRO}-rmw-cyclonedds-cpp \
        ros-${ROS_DISTRO}-joint-state-publisher-gui \
        ros-${ROS_DISTRO}-xacro \
        libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
        bluez libudev-dev udev \
        libxcb-xinerama0 libxcb-cursor0 qtbase5-dev \
        pkg-config tmux && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p ${ROS_WORKSPACE}/src
WORKDIR ${ROS_WORKSPACE}

RUN rosdep init || true && rosdep update

RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /root/.bashrc
RUN echo "source "${ROS_WORKSPACE}/install/setup.bash" >> /root/.bashrc

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]