controller:
  joint_state:
    type: joint_state_controller/JointStateController
    publish_rate: 30
  hand_state:
    type: joint_state_controller/JointStateController
    publish_rate: 30
  trajectory:
    type: position_controllers/JointTrajectoryController # Position interface because we are directly passing on commands
    allow_partial_joints_goal: true
    publish_rate: 30
    joints:
      - l_thumb_brake # FFB
      - l_index_brake # FFB
      - l_middle_brake # FFB
      - l_ring_brake # FFB
      - l_pinky_brake # FFB
      - l_thumb_cmc # Buzzer
      - l_index_mcp # Buzzer
      - l_middle_mcp # Buzzer
      - l_ring_mcp # Buzzer
      - l_pinky_mcp # Buzzer
