/**:
  ros__parameters:
    pinch_calibration_min:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    pinch_calibration_max:
    - 100.0
    - 100.0
    - 100.0
    - 100.0
/senseglove/glove0/rh/**:
  ros__parameters:
    pinch_calibration_max:
    - 100.0
    - 100.0
    - 100.0
    - 100.0
    pinch_calibration_min:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
/senseglove/glove0/lh/**:
  ros__parameters:
    pinch_calibration_max:
    - 100.0
    - 100.0
    - 100.0
    - 100.0
    pinch_calibration_min:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
/senseglove/glove1/rh/**:
  ros__parameters:
    pinch_calibration_max:
    - 100.0
    - 100.0
    - 100.0
    - 100.0
    pinch_calibration_min:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
/senseglove/glove1/lh/**:
  ros__parameters:
    pinch_calibration_max:
    - 100.0
    - 100.0
    - 100.0
    - 100.0
    pinch_calibration_min:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
