/**/controller_manager:
  ros__parameters:
    update_rate: 60    

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

/**/haptics_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - l_thumb_brake
      - l_index_brake
      - l_middle_brake
      - l_ring_brake
      - l_pinky_brake
      - l_thumb_dip
      - l_index_dip
      - l_middle_dip
      - l_ring_dip
      - l_pinky_dip
    interface_name: effort