/**/controller_manager:
  ros__parameters:
    update_rate: 60    

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

/**/senseglove_state_broadcaster:
  ros__parameters:
    type: senseglove_state_broadcaster/SenseGloveStateBroadcaster
    topic_name: senseglove_states
    frame_id: world
    joints:
      - r_thumb_mcp
      - r_thumb_pip
      - r_thumb_dip
      - r_thumb_brake
      - r_index_mcp
      - r_index_pip
      - r_index_dip
      - r_index_brake
      - r_middle_mcp
      - r_middle_pip
      - r_middle_dip
      - r_middle_brake
      - r_ring_mcp
      - r_ring_pip
      - r_ring_dip
      - r_ring_brake
      - r_pinky_mcp
      - r_pinky_pip
      - r_pinky_dip
      - r_pinky_brake

/**/haptics_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - r_thumb_brake   # FFB
      - r_index_brake   # FFB
      - r_middle_brake  # FFB
      - r_ring_brake    # FFB
      - r_thumb_dip     # Buzzer
      - r_index_dip     # Buzzer
      - r_thumper       # Buzzer - Thumper
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    action_monitor_rate: 60.0
    allow_partial_joints_goal: true
    interpolate_from_desired_state: true
    constraints:
      goal_time: 0.05